import type { Metadata } from "next";
import "./globals.css";
import Header from "../Components/commoncomponents/Header";
import Footer from "@/Components/commoncomponents/Footer";
import SplashScreen from "@/Components/Splashscreen/SplashScreen";  // Import SplashScreen component


export const metadata: Metadata = {
  title: "Ikaaya Realty",
  description: "Generated by create next app",
};

// const montserrat = localFont({ src: "../public/fonts/Montserrat-Regular.ttf", variable: "--font-montserrat" });


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* Splash Screen Component */}
        <SplashScreen />
        
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
